import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Content, fetchOneEntry } from "@builder.io/sdk-react";
import { LiveChatComponent } from "@/components/liveChat";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <LiveChat />
      </body>
    </html>
  );
}

const builderApiKey = process.env.NEXT_PUBLIC_BUILDER_API_KEY ?? "";

async function LiveChat() {
  const content = await fetchOneEntry({
    apiKey: builderApiKey,
    model: "live-chat-demo",
  });

  return (
    <Content
      apiKey={process.env.NEXT_PUBLIC_BUILDER_API_KEY ?? ""}
      content={content}
      model="live-chat-demo"
      customComponents={[LiveChatComponent]}
    />
  );
}
